### ISSUE TITLE
Error occurs when I use the image to image function

### ISSUE THREAD

**Issue by gaodianzhuo** [0xbitches/ComfyUI-LCM#13]
Error occurs when I use the image to image function,
text to image works fine,thanks.

ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "/media/arthur/data/model/ComfyUI/execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/media/arthur/data/model/ComfyUI/execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/media/arthur/data/model/ComfyUI/execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/media/arthur/data/model/ComfyUI/custom_nodes/ComfyUI-LCM/nodes.py", line 132, in sample
    result = self.pipe(
  File "/home/arthur/miniconda3/envs/dd/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/media/arthur/data/model/ComfyUI/custom_nodes/ComfyUI-LCM/lcm/lcm_i2i_pipeline.py", line 304, in __call__
    self.scheduler.set_timesteps(strength, num_inference_steps, lcm_origin_steps)
  File "/home/arthur/miniconda3/envs/dd/lib/python3.10/site-packages/diffusers/schedulers/scheduling_lcm.py", line 376, in set_timesteps
    timesteps = lcm_origin_timesteps[::-skipping_step][:num_inference_steps]
TypeError: slice indices must be integers or None or have an __index__ method

**Comment by DenkingOfficial** [comment]
Same error
```bash
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "C:\Codding\ComfyUI\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\Codding\ComfyUI\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\Codding\ComfyUI\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\Codding\ComfyUI\ComfyUI\custom_nodes\ComfyUI-LCM\nodes.py", line 129, in sample
    result = self.pipe(
  File "C:\Codding\ComfyUI\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Codding\ComfyUI\ComfyUI\custom_nodes\ComfyUI-LCM\lcm\lcm_i2i_pipeline.py", line 304, in __call__
    self.scheduler.set_timesteps(strength, num_inference_steps, lcm_origin_steps)
  File "C:\Codding\ComfyUI\python_embeded\lib\site-packages\diffusers\schedulers\scheduling_lcm.py", line 377, in set_timesteps
    timesteps = lcm_origin_timesteps[::-skipping_step][:num_inference_steps]
TypeError: slice indices must be integers or None or have an __index__ method
```
