### ISSUE TITLE
Node not recognized 

### ISSUE THREAD

**Issue by moon47usaco** [0xbitches/ComfyUI-LCM#16]
I have installed and re-installed via the Manager and via git clone. Comfy always complains that LCM sampler is missing and is red.

![Screenshot 2023-11-07 195146](https://github.com/0xbitches/ComfyUI-LCM/assets/15712871/12de088a-07ac-4c44-b86d-33b700bc48a8)
![Screenshot 2023-11-07 195744](https://github.com/0xbitches/ComfyUI-LCM/assets/15712871/27376a36-4a83-412e-9d57-042c653b682c)

**Comment by moon47usaco** [comment]
Everything updated via manager as well...

**Comment by justanotherbug** [comment]
Same here. 
Here is the output from the command window.

w:\Ai\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
** ComfyUI start up time: 2023-11-08 08:55:23.839211

Prestartup times for custom nodes:
   0.0 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 12288 MB, total RAM 32669 MB
xformers version: 0.0.22.post7+cu118
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using xformers cross attention
### Loading: ComfyUI-Impact-Pack (V4.28.2)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.3)
### Loading: ComfyUI-Inspire-Pack (V0.33)
Package diffusers is already installed.
Traceback (most recent call last):
  File "w:\Ai\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LCM\__init__.py", line 25, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LCM\nodes.py", line 3, in <module>
    from .lcm.lcm_i2i_pipeline import LatentConsistencyModelImg2ImgPipeline
  File "W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LCM\lcm\lcm_i2i_pipeline.py", line 28, in <module>
    from diffusers.image_processor import VaeImageProcessor, PipelineImageInput
ImportError: cannot import name 'PipelineImageInput' from 'diffusers.image_processor' (w:\Ai\ComfyUI_windows_portable\python_embeded\lib\site-packages\diffusers\image_processor.py)

Cannot import W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LCM module for custom nodes: cannot import name 'PipelineImageInput' from 'diffusers.image_processor' (w:\Ai\ComfyUI_windows_portable\python_embeded\lib\site-packages\diffusers\image_processor.py)
### Loading: ComfyUI-Manager (V0.36.1)
### ComfyUI Revision: 1643 [dd116abf] | Released on '2023-11-02'
[SD Prompt Reader] Node version: 1.0.1
[SD Prompt Reader] Core version: 1.3.4
Comfyroll Custom Nodes: Loaded
Registered sys.path: ['W:\\Ai\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\__init__.py', 'W:\\Ai\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\custom_pycocotools', 'W:\\Ai\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\custom_oneformer', 'W:\\Ai\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\custom_mmpkg', 'W:\\Ai\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\custom_midas_repo', 'W:\\Ai\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\custom_detectron2', 'W:\\Ai\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\controlnet_aux', 'W:\\Ai\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src', 'W:\\Ai\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI_Comfyroll_CustomNodes\\nodes\\comfy', 'W:\\Ai\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI_Comfyroll_CustomNodes\\nodes\\comfy', 'W:\\Ai\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI_Comfyroll_CustomNodes\\nodes\\comfy', 'W:\\Ai\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI_Comfyroll_CustomNodes\\nodes\\comfy', 'W:\\Ai\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-WD14-Tagger\\comfy', 'W:\\Ai\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-Custom-Scripts', 'w:\\Ai\\ComfyUI_windows_portable\\python_embeded\\lib\\site-packages\\git\\ext\\gitdb', 'W:\\Ai\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\cg-prompt-info', 'W:\\Ai\\ComfyUI_windows_portable\\ComfyUI\\comfy', 'w:\\Ai\\ComfyUI_windows_portable\\ComfyUI', 'w:\\Ai\\ComfyUI_windows_portable\\python_embeded\\python310.zip', 'w:\\Ai\\ComfyUI_windows_portable\\python_embeded', 'w:\\Ai\\ComfyUI_windows_portable\\python_embeded\\lib\\site-packages', 'w:\\Ai\\ComfyUI_windows_portable\\python_embeded\\lib\\site-packages\\win32', 'w:\\Ai\\ComfyUI_windows_portable\\python_embeded\\lib\\site-packages\\win32\\lib', 'w:\\Ai\\ComfyUI_windows_portable\\python_embeded\\lib\\site-packages\\Pythonwin', 'W:\\Ai\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-Impact-Pack\\modules', 'W:\\Ai\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-Impact-Pack\\impact_subpack', '../..']
W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py:28: UserWarning: DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly
  warnings.warn("DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly")
Using xformers cross attention
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!
Total VRAM 12288 MB, total RAM 32669 MB
xformers version: 0.0.22.post7+cu118
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
VAE dtype: torch.bfloat16
Searge-SDXL v4.3.1 in W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\SeargeSDXL
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 197 nodes successfully.

        "Art is the mirror that reflects the beauty within us." - Unknown


Import times for custom nodes:
   0.0 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\LatentByRatio.py
   0.0 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\SDXLMixSampler.py
   0.0 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\SD-Latent-Upscaler
   0.0 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\LoadLoraWithTags
   0.0 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\PPF_Noise_ComfyUI
   0.0 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Noise
   0.0 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\sd-dynamic-thresholding
   0.0 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Cutoff
   0.0 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Lora-Auto-Trigger-Words
   0.0 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\IPAdapter-ComfyUI
   0.0 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Embedding_Picker
   0.0 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_PoP
   0.0 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\wlsh_nodes
   0.0 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg-prompt-info
   0.0 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
   0.0 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
   0.0 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy-image-saver
   0.0 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.0 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.0 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.1 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.1 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-prompt-reader-node
   0.1 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\facerestore_cf
   0.1 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_smZNodes
   0.5 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   0.7 seconds (IMPORT FAILED): W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LCM
   0.7 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\SeargeSDXL
   2.1 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   2.9 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
